#if !canImport(ObjectiveC)
import XCTest

extension ValidationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ValidationTests = [
        ("testAlphanumeric", testAlphanumeric),
        ("testASCII", testASCII),
        ("testCountCharacters", testCountCharacters),
        ("testCountItems", testCountItems),
        ("testEmail", testEmail),
        ("testEmpty", testEmpty),
        ("testRange", testRange),
        ("testURL", testURL),
        ("testValidate", testValidate),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ValidationTests.__allTests__ValidationTests),
    ]
}
#endif
